name: zx_tape_player
description: ZX Tape Player makes able uploading of TAP/TZX files to ZX Spectrum compatible computers.

publish_to: 'none'

version: 1.1.1+19

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_typeahead: ^5.2.0
  package_info_plus: ^9.0.0
  http: ^1.6.0
  easy_localization: ^3.0.8
  file_picker: ^10.3.10
  cached_network_image: ^3.4.1
  pull_to_refresh_flutter3: ^2.0.2
  carousel_slider: ^5.0.0
  just_audio: ^0.9.40
  flutter_spinkit: ^5.2.1
  rxdart: ^0.28.0
  crypto: ^3.0.7
  get_it: ^9.0.0
  url_launcher: ^6.3.2
  marquee_widget: ^1.2.0
  archive: ^4.0.9
  zx_tape_to_wav: ^3.1.0+12
  sound_mode: ^3.0.0
  shared_preferences: ^2.5.5
  internet_connection_checker: ^3.0.1
  wakelock_plus: ^1.2.8
  volume_controller: ^2.0.7
  share_plus: ^10.1.4
  permission_handler: ^11.3.1
  in_app_review: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  build_runner: ^2.4.14

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/icons/launcher/ios.png"
  image_path_android: "assets/icons/launcher/android.png"
  adaptive_icon_foreground: "assets/icons/launcher/android-foreground.png"
  adaptive_icon_background: "assets/icons/launcher/android-background.png"

flutter_native_splash:
  color: "#546B7F"
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash/logo.png
    - assets/images/splash/spool.png
    - assets/images/home/search-icon.png
    - assets/translations/
    - assets/sounds/empty.wav

  fonts:
    - family: ZxSpectrum
      fonts:
        - asset: assets/fonts/zx_spectrum-7.ttf
