#!/usr/bin/env bash
# Generates linux/packaging/appimage/make_config.yaml with an `include:`
# block listing libmpv.so.2 and its full shared-library closure, minus the
# GTK-3 baseline (guaranteed present on any host that can run a Flutter
# Linux app at all) and the glibc core.
#
# Why generated and not committed statically: the closure is host-specific —
# library sonames differ between distro releases (e.g. libavcodec.so.60 on
# Ubuntu 24.04 vs .62 on 26.04), so the list must be computed on the machine
# that runs `fastforge release --jobs linux-appimage`.
#
# Requirements on the build host:
#   - libmpv (apt install libmpv-dev mpv)
#   - the committed `bin/locate` shim first on PATH when `fastforge release`
#     runs (flutter_app_packager resolves include: entries via `locate`; the
#     shim echoes our absolute paths back — no plocate/updatedb needed).
#
# Known limitation: flutter_app_packager copies include: entries flat into
# AppDir/usr/lib — directories (ALSA plugin dir, /usr/share/alsa configs)
# cannot be bundled this way. Audio output therefore still relies on the
# host's ALSA/PulseAudio data files, which every desktop installation has;
# only MediaKit.ensureInitialized()'s dlopen of libmpv is made self-contained.
set -euo pipefail

cd "$(dirname "$0")"

# No early `exit` in awk: with pipefail it would SIGPIPE ldconfig (exit 141).
resolve() {
    ldconfig -p | awk -v lib="$1" '$1 == lib && !found {print $NF; found=1}'
}

MPV="$(resolve libmpv.so.2)"
GTK="$(resolve libgtk-3.so.0)"
[ -n "$MPV" ] || { echo "libmpv.so.2 not found — apt install libmpv-dev mpv" >&2; exit 1; }
[ -n "$GTK" ] || { echo "libgtk-3.so.0 not found — install GTK 3" >&2; exit 1; }

closure() {
    ldd "$1" | awk '/=>/ {print $3}' | grep -v '^$' | LC_ALL=C sort -u
}

# glibc core + dynamic loader: always provided by the host, never bundled.
GLIBC_CORE='ld-linux|libc\.so|libm\.so|libmvec\.so|libdl\.so|libpthread\.so|librt\.so|libresolv\.so|libstdc\+\+|libgcc_s'

# GL-rendering stack only — the narrow, correct excludelist for this app.
# glvnd's libGL/libEGL/libGLX/libGLdispatch dispatch to a vendor ICD + DRI
# driver matched to the host kernel/GPU; a bundled copy that shadows the
# host's aborts GTK rendering with "No provider of eglGetPlatformDisplayEXT".
# libgbm/libdrm/libglapi are the mesa core those drivers link, and the
# Flutter engine itself dlopens libGLESv2 — all must come from the host.
#
# Everything ELSE that libmpv NEEDs is bundled, even VA-API/VDPAU/Vulkan:
# for audio-only playback those are referenced (so dlopen(libmpv) resolves
# its NEEDED table) but never initialize a GPU driver, so a bundled copy is
# safe and spares the host from providing them. The X11/Wayland CLIENT libs
# and audio clients (libasound, libpulse, libpipewire, libjack, libsndio)
# are bundled too — ABI-stable and frequently absent on minimal hosts.
DRIVER_STACK='/(libEGL|libGLESv[0-9]|libGLX|libGLdispatch|libOpenGL|libGL|libglapi|libgbm|libdrm)\.so'

# NOTE on libasound: it is bundled (it falls out of libmpv's closure here,
# and the Flutter volume_controller plugin links it directly so the maker's
# auto-closure would bundle it regardless). A bundled libasound has the
# standard compiled-in plugin dir (/usr/lib/<triplet>/alsa-lib), so on a real
# desktop it finds the host's ALSA plugins there and works. A minimal
# container without libasound2-plugins shows a non-fatal config-hook error —
# that is a test-environment gap, not a packaging defect.
INCLUDE_LIBS=$(LC_ALL=C comm -23 <(closure "$MPV") <(closure "$GTK") \
    | grep -vE "$GLIBC_CORE" | grep -vE "$DRIVER_STACK" || true)

{
    cat <<'YAML'
# AUTO-GENERATED by generate_make_config.sh — do not edit the include: list
# by hand; re-run the script instead. The static metadata below is the
# source of truth and is mirrored inside the generator.
display_name: ZX Tape Player
icon: assets/icons/launcher/android.png
generic_name: ZX Spectrum tape player
categories:
  - AudioVideo
  - Audio
  - Player
keywords:
  - ZX
  - Spectrum
  - tape
  - TAP
  - TZX
  - retro
startup_notify: true
include:
YAML
    echo "  - $MPV"
    while IFS= read -r lib; do
        [ -n "$lib" ] && echo "  - $lib"
    done <<< "$INCLUDE_LIBS"
} > make_config.yaml

COUNT=$(grep -c '^  - ' make_config.yaml)
echo "make_config.yaml generated with $COUNT bundled libraries."
